"""
COSMIN Risk of Bias Checklist V3.0 — Complete encoding of all 10 boxes.

Transcribed verbatim from the official PDF:
  COSMIN Risk of Bias checklist, Version 3.0, 27 August 2024
  LB Mokkink, E Elsman, CB Terwee. (2024).
  https://www.cosmin.nl/wp-content/uploads/COSMIN-RoB-checklist-for-PROMs-V3_1.pdf

Rating levels: very_good / adequate / doubtful / inadequate / NA
Empty string "" means that rating level is greyed-out (not applicable for that standard).
"""

COSMIN_BOXES = [
    # ========================================================================
    # BOX 1: PROM DEVELOPMENT
    # ========================================================================
    {
        "box_number": 1,
        "name": "PROM development",
        "description": "Evaluates the quality of the PROM development process including concept elicitation and pilot testing.",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "1a",
                "name": "Concept elicitation study (relevance and comprehensiveness)",
                "section_group": "Concept elicitation",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "Was the concept elicitation study performed in a sample representing the target population for which the PROM was developed?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Study performed in a sample representing the target population.",
                        "rating_adequate": "Assumable that the study was performed in a sample representing the target population, but not clearly described.",
                        "rating_doubtful": "Doubtful whether the study was performed in a sample representing the target population.",
                        "rating_inadequate": "Study not performed in a sample representing the target population.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "Was an appropriate qualitative data collection method used to identify relevant items for a new PROM?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Widely recognized or well justified qualitative method used, suitable for the construct and study population.",
                        "rating_adequate": "Assumable that the qualitative method was appropriate and suitable for the construct and study population, but not clearly described.",
                        "rating_doubtful": "Only quantitative (survey) method(s) used or doubtful whether the method was suitable for the construct and study population.",
                        "rating_inadequate": "Method used not appropriate or not suitable for the construct or study population.",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "Were skilled group moderators/interviewers used?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Skilled group moderators/interviewers used.",
                        "rating_adequate": "Group moderators/interviewers had limited experience or were trained specifically for the study.",
                        "rating_doubtful": "Not clear if group moderators/interviewers were trained or group moderators/interviewers not trained and no experience.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 4,
                        "question_text": "Were the group meetings or interviews based on an appropriate topic or interview guide?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Appropriate topic or interview guide.",
                        "rating_adequate": "Assumable that the topic or interview guide was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear if a topic guide was used or doubtful if topic or interview guide was appropriate or no guide.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 5,
                        "question_text": "Were the group meetings or interviews recorded and transcribed verbatim?",
                        "section_group": "Design requirements",
                        "rating_very_good": "All group meetings or interviews were recorded and transcribed verbatim.",
                        "rating_adequate": "Assumable that all group meetings or interviews were recorded and transcribed verbatim, but not clearly described.",
                        "rating_doubtful": "Not clear if all group meetings of interviews were recorded and transcribed verbatim or recordings not transcribed verbatim or only notes were made during the group meetings/interviews.",
                        "rating_inadequate": "No recording and no notes.",
                        "na_allowed": True,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 6,
                        "question_text": "Was an appropriate approach used to analyse the data?",
                        "section_group": "Design requirements",
                        "rating_very_good": "A widely recognized or well justified approach was used.",
                        "rating_adequate": "Assumable that the approach was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear what approach was used or doubtful whether the approach was appropriate.",
                        "rating_inadequate": "Approach not appropriate.",
                        "na_allowed": False,
                        "sort_order": 6,
                    },
                    {
                        "standard_number": 7,
                        "question_text": "Was at least part of the data coded independently?",
                        "section_group": "Design requirements",
                        "rating_very_good": "At least 50% of the data was coded by at least two researchers independently.",
                        "rating_adequate": "11-49% of the data was coded by at least two researchers independently.",
                        "rating_doubtful": "Doubtful if two researchers were involved in the coding or only 1-10% of the data was coded by at least two researchers independently.",
                        "rating_inadequate": "Only one researcher was involved in coding or no coding.",
                        "na_allowed": True,
                        "sort_order": 7,
                    },
                    {
                        "standard_number": 8,
                        "question_text": "Was data collection continued until saturation was reached?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Evidence provided that saturation was reached.",
                        "rating_adequate": "Assumable that saturation was reached.",
                        "rating_doubtful": "Doubtful whether saturation was reached.",
                        "rating_inadequate": "Evidence suggests that saturation was not reached.",
                        "na_allowed": True,
                        "sort_order": 8,
                    },
                    {
                        "standard_number": 9,
                        "question_text": "For quantitative studies (surveys): was the sample size appropriate?",
                        "section_group": "Design requirements",
                        "rating_very_good": ">=100.",
                        "rating_adequate": "50-99.",
                        "rating_doubtful": "30-49.",
                        "rating_inadequate": "<30.",
                        "na_allowed": True,
                        "sort_order": 9,
                    },
                    {
                        "standard_number": 10,
                        "question_text": "Were there any other important flaws in the design or methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 10,
                    },
                ],
            },
            {
                "sub_box_code": "1b",
                "name": "Pilot study (Cognitive interview study or other pilot test) (comprehensibility)",
                "section_group": "Pilot study",
                "sort_order": 2,
                "standards": [
                    {
                        "standard_number": 11,
                        "question_text": "Was the pilot study performed in a sample representing the target population for which the PROM was developed?",
                        "section_group": "Comprehensibility",
                        "rating_very_good": "Study performed in a sample representing the target population AND Sample was not included in the concept elicitation study.",
                        "rating_adequate": "Assumable that the study was performed in a sample representing the target population but not clearly described, or sample was included in the concept elicitation study.",
                        "rating_doubtful": "Doubtful whether the study was performed in a sample representing the target population.",
                        "rating_inadequate": "Study not performed in a sample representing the target population.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 12,
                        "question_text": "Was the comprehensibility assessed of the PROM instructions, items, response options, and recall period?",
                        "section_group": "Comprehensibility",
                        "rating_very_good": "Comprehensibility of the PROM instructions, items, response options, and recall period was assessed.",
                        "rating_adequate": "",
                        "rating_doubtful": "Not clear if patients were asked about the comprehensibility of all items, response options, instructions, and recall period OR patients not asked about the comprehensibility of the PROM instructions or the recall period.",
                        "rating_inadequate": "Patients were not asked about the comprehensibility of all items and response options.",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 13,
                        "question_text": "Were all items tested in their final form?",
                        "section_group": "Comprehensibility",
                        "rating_very_good": "All items were tested in their final form.",
                        "rating_adequate": "Assumable that all items were tested in their final form, but not clearly described.",
                        "rating_doubtful": "Not clear if all items were tested in their final form.",
                        "rating_inadequate": "Items were not tested in their final form or items were not re-tested after substantial adjustments.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 14,
                        "question_text": "Was an appropriate qualitative method used?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Widely recognized or well justified qualitative method used.",
                        "rating_adequate": "Assumable that the method was appropriate but not clearly described.",
                        "rating_doubtful": "Only quantitative (survey) method(s) used or doubtful whether the method was appropriate.",
                        "rating_inadequate": "Method used not appropriate.",
                        "na_allowed": False,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 15,
                        "question_text": "Was each item tested in an appropriate number of patients?",
                        "section_group": "Design requirements",
                        "rating_very_good": "For qualitative studies: >=7. For quantitative (survey) studies: >=50.",
                        "rating_adequate": "For qualitative studies: 4-6. For quantitative (survey) studies: >=30.",
                        "rating_doubtful": "For qualitative studies: <4 or not clear. For quantitative (survey) studies: <30 or not clear.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 16,
                        "question_text": "Were skilled interviewers used?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Skilled interviewers used.",
                        "rating_adequate": "Interviewers had limited experience or were trained specifically for the study.",
                        "rating_doubtful": "Not clear if interviewers were trained OR interviewers were not trained and had no experience.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 6,
                    },
                    {
                        "standard_number": 17,
                        "question_text": "Were the interviews based on an appropriate interview guide?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Appropriate topic or interview guide.",
                        "rating_adequate": "Assumable that the topic or interview guide was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear if a topic guide was used or doubtful if topic or interview guide was appropriate OR no guide.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 7,
                    },
                    {
                        "standard_number": 18,
                        "question_text": "Were the interviews recorded and transcribed verbatim?",
                        "section_group": "Design requirements",
                        "rating_very_good": "All interviews were recorded and transcribed verbatim.",
                        "rating_adequate": "Assumable that all interviews were recorded and transcribed verbatim, but not clearly described.",
                        "rating_doubtful": "Not clear if all interviews were recorded and transcribed verbatim OR recordings not transcribed verbatim OR only notes were made during the interviews.",
                        "rating_inadequate": "No recording and no notes.",
                        "na_allowed": True,
                        "sort_order": 8,
                    },
                    {
                        "standard_number": 19,
                        "question_text": "Was an appropriate approach used to analyse the data?",
                        "section_group": "Design requirements",
                        "rating_very_good": "A widely recognized or well justified approach was used.",
                        "rating_adequate": "Assumable that the approach was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear what approach was used OR doubtful whether the approach was appropriate.",
                        "rating_inadequate": "Approach not appropriate.",
                        "na_allowed": False,
                        "sort_order": 9,
                    },
                    {
                        "standard_number": 20,
                        "question_text": "Were at least two researchers involved in the analysis?",
                        "section_group": "Design requirements",
                        "rating_very_good": "At least two researchers involved in the analysis.",
                        "rating_adequate": "Assumable that at least two researchers were involved in the analysis, but not clearly described.",
                        "rating_doubtful": "Not clear if two researchers were included in the analysis OR only one researcher involved in the analysis.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 10,
                    },
                    {
                        "standard_number": 21,
                        "question_text": "Were problems regarding the comprehensibility of the PROM instructions, items, response options, and recall period appropriately addressed by adapting the PROM?",
                        "section_group": "Comprehensibility",
                        "rating_very_good": "No problems found OR problems appropriately addressed and PROM was adapted and re-tested if necessary.",
                        "rating_adequate": "Assumable that there were no problems or that problems were appropriately addressed, but not clearly described.",
                        "rating_doubtful": "Not clear if there were problems OR doubtful if problems were appropriately addressed.",
                        "rating_inadequate": "Problems not appropriately addressed OR PROM was adapted but items were not re-tested after substantial adjustments.",
                        "na_allowed": True,
                        "sort_order": 11,
                    },
                    {
                        "standard_number": 22,
                        "question_text": "Were there any other important flaws in the design or methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 12,
                    },
                ],
            },
        ],
    },
    # ========================================================================
    # BOX 2: CONTENT VALIDITY
    # ========================================================================
    {
        "box_number": 2,
        "name": "Content validity",
        "description": "Evaluates the degree to which the content of the PROM is an adequate reflection of the construct to be measured.",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "2a",
                "name": "Asking patients about relevance",
                "section_group": "Patients - relevance",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "Was an appropriate method used to ask patients whether each item is relevant for their experience with the condition?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Widely recognized or well justified method used.",
                        "rating_adequate": "Only quantitative (survey) method(s) used or assumable that the method was appropriate but not clearly described.",
                        "rating_doubtful": "Not clear if patients were asked whether each item is relevant OR doubtful whether the method was appropriate.",
                        "rating_inadequate": "Method used not appropriate OR patients not asked about the relevance of all items.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "Was each item tested in an appropriate number of patients?",
                        "section_group": "Design requirements",
                        "rating_very_good": "For qualitative studies: >=7. For quantitative (survey) studies: >=50.",
                        "rating_adequate": "For qualitative studies: 4-6. For quantitative (survey) studies: >=30.",
                        "rating_doubtful": "For qualitative studies: <4 or not clear. For quantitative (survey) studies: <30 or not clear.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "Were skilled group moderators/interviewers used?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Skilled group moderators/interviewers used.",
                        "rating_adequate": "Group moderators/interviewers had limited experience or were trained specifically for the study.",
                        "rating_doubtful": "Not clear if group moderators/interviewers were trained OR group moderators/interviewers were not trained and had no experience.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 4,
                        "question_text": "Were the group meetings or interviews based on an appropriate topic or interview guide?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Appropriate topic or interview guide.",
                        "rating_adequate": "Assumable that the topic or interview guide was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear if a topic guide was used OR doubtful if topic or interview guide was appropriate OR no guide.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 5,
                        "question_text": "Were the group meetings or interviews recorded and transcribed verbatim?",
                        "section_group": "Design requirements",
                        "rating_very_good": "All group meetings or interviews were recorded and transcribed verbatim.",
                        "rating_adequate": "Assumable that all group meetings or interviews were recorded and transcribed verbatim, but not clearly described.",
                        "rating_doubtful": "Not clear if all group meetings or interviews were recorded and transcribed verbatim OR recordings not transcribed verbatim OR only notes were made during the group meetings/interviews.",
                        "rating_inadequate": "No recording and no notes.",
                        "na_allowed": True,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 6,
                        "question_text": "Was an appropriate approach used to analyse the data?",
                        "section_group": "Analyses",
                        "rating_very_good": "A widely recognized or well justified approach was used.",
                        "rating_adequate": "Assumable that the approach was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear what approach was used OR doubtful whether the approach was appropriate.",
                        "rating_inadequate": "Approach not appropriate.",
                        "na_allowed": False,
                        "sort_order": 6,
                    },
                    {
                        "standard_number": 7,
                        "question_text": "Were at least two researchers involved in the analysis?",
                        "section_group": "Analyses",
                        "rating_very_good": "At least two researchers involved in the analysis.",
                        "rating_adequate": "Assumable that at least two researchers were involved in the analysis, but not clearly described.",
                        "rating_doubtful": "Not clear if two researchers were included in the analysis OR only one researcher involved in the analysis.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 7,
                    },
                    {
                        "standard_number": 8,
                        "question_text": "Were there any other important flaws in the design or methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 8,
                    },
                ],
            },
            {
                "sub_box_code": "2b",
                "name": "Asking patients about comprehensiveness",
                "section_group": "Patients - comprehensiveness",
                "sort_order": 2,
                "standards": [
                    {
                        "standard_number": 9,
                        "question_text": "Was an appropriate method used for assessing the comprehensiveness of the PROM?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Widely recognized or well justified method used.",
                        "rating_adequate": "Only quantitative (survey) method(s) used OR assumable that the method was appropriate but not clearly described.",
                        "rating_doubtful": "Doubtful whether the method was appropriate.",
                        "rating_inadequate": "Method used not appropriate.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 10,
                        "question_text": "Was the PROM tested in an appropriate number of patients?",
                        "section_group": "Design requirements",
                        "rating_very_good": "For qualitative studies: >=7. For quantitative (survey) studies: >=50.",
                        "rating_adequate": "For qualitative studies: 4-6. For quantitative (survey) studies: >=30.",
                        "rating_doubtful": "For qualitative studies: <4 or not clear. For quantitative (survey) studies: <30 or not clear.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 11,
                        "question_text": "Were skilled group moderators/interviewers used?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Skilled group moderators/interviewers used.",
                        "rating_adequate": "Group moderators/interviewers had limited experience or were trained specifically for the study.",
                        "rating_doubtful": "Not clear if group moderators/interviewers were trained OR group moderators/interviewers were not trained and had no experience.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 12,
                        "question_text": "Were the group meetings or interviews based on an appropriate topic or interview guide?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Appropriate topic or interview guide.",
                        "rating_adequate": "Assumable that the topic or interview guide was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear if a topic guide was used OR doubtful if topic or interview guide was appropriate OR no guide.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 13,
                        "question_text": "Were the group meetings or interviews recorded and transcribed verbatim?",
                        "section_group": "Design requirements",
                        "rating_very_good": "All group meetings or interviews were recorded and transcribed verbatim.",
                        "rating_adequate": "Assumable that all group meetings or interviews were recorded and transcribed verbatim, but not clearly described.",
                        "rating_doubtful": "Not clear if all group meetings or interviews were recorded and transcribed verbatim OR recordings not transcribed verbatim OR only notes were made during the group meetings/interviews.",
                        "rating_inadequate": "No recording and no notes.",
                        "na_allowed": True,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 14,
                        "question_text": "Was an appropriate approach used to analyse the data?",
                        "section_group": "Analyses",
                        "rating_very_good": "A widely recognized or well justified approach was used.",
                        "rating_adequate": "Assumable that the approach was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear what approach was used OR doubtful whether the approach was appropriate.",
                        "rating_inadequate": "Approach not appropriate.",
                        "na_allowed": False,
                        "sort_order": 6,
                    },
                    {
                        "standard_number": 15,
                        "question_text": "Were at least two researchers involved in the analysis?",
                        "section_group": "Analyses",
                        "rating_very_good": "At least two researchers involved in the analysis.",
                        "rating_adequate": "Assumable that at least two researchers were involved in the analysis, but not clearly described.",
                        "rating_doubtful": "Not clear if two researchers were included in the analysis OR only one researcher involved in the analysis.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 7,
                    },
                    {
                        "standard_number": 16,
                        "question_text": "Were there any other important flaws in the design or methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 8,
                    },
                ],
            },
            {
                "sub_box_code": "2c",
                "name": "Asking patients about comprehensibility",
                "section_group": "Patients - comprehensibility",
                "sort_order": 3,
                "standards": [
                    {
                        "standard_number": 17,
                        "question_text": "Was an appropriate qualitative method used for assessing the comprehensibility of the PROM instructions, items, response options, and recall period?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Widely recognized or well justified qualitative method used.",
                        "rating_adequate": "Assumable that the method was appropriate but not clearly described.",
                        "rating_doubtful": "Only quantitative (survey) method(s) used OR doubtful whether the method was appropriate OR not clear if patients were asked about the comprehensibility of the items, response options, instructions, and recall period OR patients not asked about the comprehensibility of the PROM instructions or the recall period.",
                        "rating_inadequate": "Method used not appropriate OR patients not asked about the comprehensibility of the items, response options, and recall period.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 18,
                        "question_text": "Was each item tested in an appropriate number of patients?",
                        "section_group": "Design requirements",
                        "rating_very_good": "For qualitative studies: >=7. For quantitative (survey) studies: >=50.",
                        "rating_adequate": "For qualitative studies: 4-6. For quantitative (survey) studies: >=30.",
                        "rating_doubtful": "For qualitative studies: <4 or not clear. For quantitative (survey) studies: <30 or not clear.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 19,
                        "question_text": "Were skilled group moderators/interviewers used?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Skilled group moderators/interviewers used.",
                        "rating_adequate": "Group moderators/interviewers had limited experience or were trained specifically for the study.",
                        "rating_doubtful": "Not clear if group moderators/interviewers were trained OR group moderators/interviewers were not trained and had no experience.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 20,
                        "question_text": "Were the group meetings or interviews based on an appropriate topic or interview guide?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Appropriate topic or interview guide.",
                        "rating_adequate": "Assumable that the topic or interview guide was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear if a topic guide was used OR doubtful if topic or interview guide was appropriate OR no guide.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 21,
                        "question_text": "Were the group meetings or interviews recorded and transcribed verbatim?",
                        "section_group": "Design requirements",
                        "rating_very_good": "All group meetings or interviews were recorded and transcribed verbatim.",
                        "rating_adequate": "Assumable that all group meetings or interviews were recorded and transcribed verbatim, but not clearly described.",
                        "rating_doubtful": "Not clear if all group meetings or interviews were recorded and transcribed verbatim OR recordings not transcribed verbatim OR only notes were made during the group meetings/interviews.",
                        "rating_inadequate": "No recording and no notes.",
                        "na_allowed": True,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 22,
                        "question_text": "Was an appropriate approach used to analyse the data?",
                        "section_group": "Analyses",
                        "rating_very_good": "A widely recognized or well justified approach was used.",
                        "rating_adequate": "Assumable that the approach was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear what approach was used OR doubtful whether the approach was appropriate.",
                        "rating_inadequate": "Approach not appropriate.",
                        "na_allowed": False,
                        "sort_order": 6,
                    },
                    {
                        "standard_number": 23,
                        "question_text": "Were at least two researchers involved in the analysis?",
                        "section_group": "Analyses",
                        "rating_very_good": "At least two researchers involved in the analysis.",
                        "rating_adequate": "Assumable that at least two researchers were involved in the analysis, but not clearly described.",
                        "rating_doubtful": "Not clear if two researchers were included in the analysis OR only one researcher involved in the analysis.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 7,
                    },
                    {
                        "standard_number": 24,
                        "question_text": "Were there any other important flaws in the design or methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 8,
                    },
                ],
            },
            {
                "sub_box_code": "2d",
                "name": "Asking professionals about relevance",
                "section_group": "Professionals - relevance",
                "sort_order": 4,
                "standards": [
                    {
                        "standard_number": 25,
                        "question_text": "Was an appropriate method used to ask professionals whether each item is relevant for the construct of interest?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Widely recognized or well justified method used.",
                        "rating_adequate": "Only quantitative (survey) method(s) used OR assumable that the method was appropriate but not clearly described.",
                        "rating_doubtful": "Not clear if professionals were asked whether each item is relevant OR doubtful whether the method was appropriate.",
                        "rating_inadequate": "Method used not appropriate OR professionals not asked about the relevance of all items.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 26,
                        "question_text": "Were professionals from all relevant disciplines included?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Professionals from all required disciplines were included.",
                        "rating_adequate": "Assumable that professionals from all required disciplines were included, but not clearly described.",
                        "rating_doubtful": "Doubtful whether professionals from all required disciplines were included OR relevant professionals were not included.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 27,
                        "question_text": "Was each item tested in an appropriate number of professionals?",
                        "section_group": "Design requirements",
                        "rating_very_good": "For qualitative studies: >=7. For quantitative (survey) studies: >=50.",
                        "rating_adequate": "For qualitative studies: 4-6. For quantitative (survey) studies: >=30.",
                        "rating_doubtful": "For qualitative studies: <4 or not clear. For quantitative (survey) studies: <30 or not clear.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 28,
                        "question_text": "Was an appropriate approach used to analyse the data?",
                        "section_group": "Analyses",
                        "rating_very_good": "A widely recognized or well justified approach was used.",
                        "rating_adequate": "Assumable that the approach was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear what approach was used OR doubtful whether the approach was appropriate.",
                        "rating_inadequate": "Approach not appropriate.",
                        "na_allowed": False,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 29,
                        "question_text": "Were at least two researchers involved in the analysis?",
                        "section_group": "Analyses",
                        "rating_very_good": "At least two researchers involved in the analysis.",
                        "rating_adequate": "Assumable that at least two researchers were involved in the analysis, but not clearly described.",
                        "rating_doubtful": "Not clear if two researchers were included in the analysis OR only one researcher involved in the analysis.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 30,
                        "question_text": "Were there any other important flaws in the design or methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 6,
                    },
                ],
            },
            {
                "sub_box_code": "2e",
                "name": "Asking professionals about comprehensiveness",
                "section_group": "Professionals - comprehensiveness",
                "sort_order": 5,
                "standards": [
                    {
                        "standard_number": 31,
                        "question_text": "Was an appropriate method used for assessing the comprehensiveness of the PROM?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Widely recognized or well justified method used.",
                        "rating_adequate": "Only quantitative (survey) method(s) used OR assumable that the method was appropriate but not clearly described.",
                        "rating_doubtful": "Doubtful whether the method was appropriate.",
                        "rating_inadequate": "Method used not appropriate.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 32,
                        "question_text": "Were professionals from all relevant disciplines included?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Professionals from all required disciplines were included.",
                        "rating_adequate": "Assumable that professionals from all required disciplines were included, but not clearly described.",
                        "rating_doubtful": "Doubtful whether professionals from all required disciplines were included OR relevant professionals were not included.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 33,
                        "question_text": "Was the PROM tested in an appropriate number of professionals?",
                        "section_group": "Design requirements",
                        "rating_very_good": "For qualitative studies: >=7. For quantitative (survey) studies: >=50.",
                        "rating_adequate": "For qualitative studies: 4-6. For quantitative (survey) studies: >=30.",
                        "rating_doubtful": "For qualitative studies: <4 or not clear. For quantitative (survey) studies: <30 or not clear.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 34,
                        "question_text": "Was an appropriate approach used to analyse the data?",
                        "section_group": "Analyses",
                        "rating_very_good": "A widely recognized or well justified approach was used.",
                        "rating_adequate": "Assumable that the approach was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear what approach was used OR doubtful whether the approach was appropriate.",
                        "rating_inadequate": "Approach not appropriate.",
                        "na_allowed": False,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 35,
                        "question_text": "Were at least two researchers involved in the analysis?",
                        "section_group": "Analyses",
                        "rating_very_good": "At least two researchers involved in the analysis.",
                        "rating_adequate": "Assumable that at least two researchers were involved in the analysis, but not clearly described.",
                        "rating_doubtful": "Not clear if two researchers were included in the analysis OR only one researcher involved in the analysis.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 36,
                        "question_text": "Were there any other important flaws in the design or methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 6,
                    },
                ],
            },
            {
                "sub_box_code": "2f",
                "name": "Asking professionals about comprehensibility",
                "section_group": "Professionals - comprehensibility",
                "sort_order": 6,
                "standards": [
                    {
                        "standard_number": 37,
                        "question_text": "Was an appropriate method used for assessing the comprehensibility of the PROM instructions, items, response options, and recall period?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Widely recognized or well justified method used.",
                        "rating_adequate": "Assumable that the method was appropriate but not clearly described.",
                        "rating_doubtful": "Only quantitative (survey) method(s) used OR doubtful whether the method was appropriate OR not clear if professionals were asked about the comprehensibility of all items, response options, instructions, and recall period OR professionals not asked about the comprehensibility of the PROM instructions or the recall period.",
                        "rating_inadequate": "Method used not appropriate OR professionals not asked about the comprehensibility of all items and response options.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 38,
                        "question_text": "Were professionals from all relevant disciplines included?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Professionals from all required disciplines were included.",
                        "rating_adequate": "Assumable that professionals from all required disciplines were included, but not clearly described.",
                        "rating_doubtful": "Doubtful whether professionals from all required disciplines were included OR relevant professionals were not included.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 39,
                        "question_text": "Was each item tested in an appropriate number of professionals?",
                        "section_group": "Design requirements",
                        "rating_very_good": "For qualitative studies: >=7. For quantitative (survey) studies: >=50.",
                        "rating_adequate": "For qualitative studies: 4-6. For quantitative (survey) studies: >=30.",
                        "rating_doubtful": "For qualitative studies: <4 or not clear. For quantitative (survey) studies: <30 or not clear.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 40,
                        "question_text": "Was an appropriate approach used to analyse the data?",
                        "section_group": "Analyses",
                        "rating_very_good": "A widely recognized or well justified approach was used.",
                        "rating_adequate": "Assumable that the approach was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear what approach was used OR doubtful whether the approach was appropriate.",
                        "rating_inadequate": "Approach not appropriate.",
                        "na_allowed": False,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 41,
                        "question_text": "Were at least two researchers involved in the analysis?",
                        "section_group": "Analyses",
                        "rating_very_good": "At least two researchers involved in the analysis.",
                        "rating_adequate": "Assumable that at least two researchers were involved in the analysis, but not clearly described.",
                        "rating_doubtful": "Not clear if two researchers were included in the analysis OR only one researcher involved in the analysis.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 42,
                        "question_text": "Were there any other important flaws in the design or methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 6,
                    },
                ],
            },
        ],
    },
    # ========================================================================
    # BOX 3: STRUCTURAL VALIDITY
    # ========================================================================
    {
        "box_number": 3,
        "name": "Structural validity",
        "description": "Evaluates the degree to which scores are an adequate reflection of the dimensionality of the construct.",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "3",
                "name": "Structural validity",
                "section_group": "Structural validity",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "For CTT: Was exploratory or confirmatory factor analysis performed?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Confirmatory factor analysis performed.",
                        "rating_adequate": "Exploratory factor analysis performed.",
                        "rating_doubtful": "Only PCA was performed.",
                        "rating_inadequate": "No exploratory or confirmatory factor analysis performed.",
                        "na_allowed": True,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "For IRT/Rasch: does the chosen model fit to the research question?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Chosen model fits well to the research question.",
                        "rating_adequate": "Assumable that the chosen model fits well to the research question.",
                        "rating_doubtful": "Doubtful if the chosen model fits well to the research question.",
                        "rating_inadequate": "Chosen model does not fit to the research question.",
                        "na_allowed": True,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "Was the sample size included in the analysis adequate?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "FA: 7 times the number of items in the tested model and >=100. Rasch/1PL models: >= 200 subjects. 2PL parametric IRT models OR Mokken scale analysis: >= 1000 subjects.",
                        "rating_adequate": "FA: at least 5 times the number of items in the tested model and >=100; OR at least 6 times the number of items in the tested model but <100. Rasch/1PL models: 100-199 subjects. 2PL parametric IRT models OR Mokken scale analysis: 500-999 subjects.",
                        "rating_doubtful": "FA: 5 times the number of items in the tested model but <100. Rasch/1PL models: 50-99 subjects. 2PL parametric IRT models OR Mokken scale analysis: 250-499 subjects.",
                        "rating_inadequate": "FA: < 5 times the number of items in the tested model. Rasch/1PL models: < 50 subjects. 2PL parametric IRT models OR Mokken scale analysis: < 250 subjects.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 4,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws (e.g. rotation method not described).",
                        "rating_inadequate": "Other important methodological flaws (e.g. inappropriate rotation method).",
                        "na_allowed": False,
                        "sort_order": 4,
                    },
                ],
            },
        ],
    },
    # ========================================================================
    # BOX 4: INTERNAL CONSISTENCY
    # ========================================================================
    {
        "box_number": 4,
        "name": "Internal consistency",
        "description": "Evaluates the degree of interrelatedness among the items.",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "4",
                "name": "Internal consistency",
                "section_group": "Internal consistency",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "For continuous scores: Was Cronbach's alpha or omega calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Cronbach's alpha, or Omega calculated.",
                        "rating_adequate": "",
                        "rating_doubtful": "Only item-total correlations calculated.",
                        "rating_inadequate": "No Cronbach's alpha and no item-total correlations calculated.",
                        "na_allowed": True,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "For dichotomous scores: Was Cronbach's alpha or KR-20 calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Cronbach's alpha or KR-20 calculated.",
                        "rating_adequate": "",
                        "rating_doubtful": "Only item-total correlations calculated.",
                        "rating_inadequate": "No Cronbach's alpha or KR-20 and no item-total correlations calculated.",
                        "na_allowed": True,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "For IRT-based scores: Was standard error of the theta (SE (theta)) or reliability coefficient of estimated latent trait value (index of subject or item) separation) calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "SE(theta) or reliability coefficient calculated.",
                        "rating_adequate": "",
                        "rating_doubtful": "",
                        "rating_inadequate": "SE(theta) or reliability coefficient NOT calculated.",
                        "na_allowed": True,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 4,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 4,
                    },
                ],
            },
        ],
    },
    # ========================================================================
    # BOX 5: CROSS-CULTURAL VALIDITY / MEASUREMENT INVARIANCE
    # ========================================================================
    {
        "box_number": 5,
        "name": "Cross-cultural validity/Measurement invariance",
        "description": "Evaluates the degree to which the performance of the items on a translated or culturally adapted PROM are an adequate reflection of the performance of the items of the original version.",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "5",
                "name": "Cross-cultural validity/Measurement invariance",
                "section_group": "Cross-cultural validity",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "Were the samples similar for relevant characteristics except for the group variable?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Evidence provided that samples were similar for relevant characteristics except group variable.",
                        "rating_adequate": "Stated (but no evidence provided) that samples were similar for relevant characteristics except group variable.",
                        "rating_doubtful": "Unclear whether samples were similar for relevant characteristics except group variable.",
                        "rating_inadequate": "Samples were NOT similar for relevant characteristics except group variable.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "Was an appropriate approach used to analyse the data?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "A widely recognized or well justified approach was used.",
                        "rating_adequate": "Assumable that the approach was appropriate, but not clearly described.",
                        "rating_doubtful": "Not clear what approach was used OR doubtful whether the approach was appropriate.",
                        "rating_inadequate": "Approach not appropriate.",
                        "na_allowed": True,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "Was the sample size included in the analysis adequate?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "MGCFA: 7 times the number of items in the model and >=100. Regression analyses or IRT/Rasch based analyses: 200 subjects per group.",
                        "rating_adequate": "5 times the number of items in the model and >=100; OR 5-7 times the number of items in the model but <100. Regression analyses or IRT/Rasch based analyses: 150 subjects per group.",
                        "rating_doubtful": "5 times the number of items in the model but <100. Regression analyses or IRT/Rasch based analyses: 100 subjects per group.",
                        "rating_inadequate": "<5 times the number of items in the model. Regression analyses or IRT/Rasch based analyses: < 100 subjects per group.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 4,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 4,
                    },
                ],
            },
        ],
    },
    # ========================================================================
    # BOX 6: RELIABILITY
    # ========================================================================
    {
        "box_number": 6,
        "name": "Reliability",
        "description": "Evaluates the proportion of total variance in the measurements due to true differences between patients.",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "6",
                "name": "Reliability",
                "section_group": "Reliability",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "Were patients stable on the construct to be measured in the time between the repeated measurements?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Evidence provided that patients were stable.",
                        "rating_adequate": "Assumable that patients were stable.",
                        "rating_doubtful": "Unclear if patients were stable.",
                        "rating_inadequate": "Patients were NOT stable.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "Was the time interval between the repeated measurements appropriate?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Time interval appropriate.",
                        "rating_adequate": "",
                        "rating_doubtful": "Doubtful if time interval was appropriate OR time interval was not stated.",
                        "rating_inadequate": "Time interval NOT appropriate.",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "Were the measurement conditions similar for the repeated measurements - except for the condition being evaluated?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Measurement conditions were similar (evidence provided).",
                        "rating_adequate": "Assumable that measurement conditions were similar.",
                        "rating_doubtful": "Unclear if measurement conditions were similar.",
                        "rating_inadequate": "Measurement conditions were NOT similar.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 4,
                        "question_text": "For continuous scores: Was the appropriate intraclass correlation coefficient (ICC) calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "ICC_agreement was or can be calculated.",
                        "rating_adequate": "(ICC_consistency, Pearson or Spearman correlation coefficient was calculated, OR the ICC model or formula was not described) WITH evidence provided that no systematic change between measurements has occurred. OR ICC_one-way was calculated.",
                        "rating_doubtful": "(ICC_consistency, Pearson or Spearman correlation coefficient was calculated OR the ICC model or formula was not described) WITHOUT evidence provided that no systematic change between measurements has occurred.",
                        "rating_inadequate": "(ICC_consistency, Pearson or Spearman correlation coefficient was calculated OR the ICC model or formula was not described) WITH evidence provided that a systematic change between measurements has occurred.",
                        "na_allowed": True,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 5,
                        "question_text": "For dichotomous scores: was kappa calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Kappa calculated.",
                        "rating_adequate": "",
                        "rating_doubtful": "",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 6,
                        "question_text": "For nominal scores: was an unweighted kappa calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Unweighted kappa calculated.",
                        "rating_adequate": "",
                        "rating_doubtful": "",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 6,
                    },
                    {
                        "standard_number": 7,
                        "question_text": "For ordinal scores: was a weighted kappa calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Weighted kappa calculated and the weighting scheme was described.",
                        "rating_adequate": "Kappa calculated, but weighting scheme not described.",
                        "rating_doubtful": "Unweighted Kappa calculated or unclear if weighting was applied.",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 7,
                    },
                    {
                        "standard_number": 8,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 8,
                    },
                ],
            },
        ],
    },
    # ========================================================================
    # BOX 7: MEASUREMENT ERROR
    # ========================================================================
    {
        "box_number": 7,
        "name": "Measurement error",
        "description": "Evaluates the systematic and random error of a patient's score not attributed to true changes in the construct.",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "7",
                "name": "Measurement error",
                "section_group": "Measurement error",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "Were patients stable on the construct to be measured in the time between the repeated measurements?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Evidence provided that patients were stable.",
                        "rating_adequate": "Assumable that patients were stable.",
                        "rating_doubtful": "Unclear if patients were stable.",
                        "rating_inadequate": "Patients were NOT stable.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "Was the time interval between the repeated measurements appropriate?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Time interval appropriate.",
                        "rating_adequate": "",
                        "rating_doubtful": "Doubtful if time interval was appropriate OR time interval was not stated.",
                        "rating_inadequate": "Time interval NOT appropriate.",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "Were the measurement conditions similar for the measurements - except for the condition being evaluated as a source of variation?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Measurement conditions were similar (evidence provided).",
                        "rating_adequate": "Assumable that measurement conditions were similar.",
                        "rating_doubtful": "Unclear if measurement conditions were similar.",
                        "rating_inadequate": "Measurement conditions were NOT similar.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 4,
                        "question_text": "For continuous scores: was the Standard Error of Measurement (SEM), Smallest Detectable Change (SDC) or Limits of Agreement (LoA) calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "SEM_agreement, SEM_one-way, SDC_agreement, or SDC_one-way was or could be calculated.",
                        "rating_adequate": "(SEM_consistency or SDC_consistency or LoA was calculated OR the SEM/SDC model or formula was not described) WITH evidence provided that no systematic change between the measurement has occurred.",
                        "rating_doubtful": "(SEM_consistency, SDC_consistency, or LoA was calculated) WITHOUT evidence provided that no systematic change between measurements has occurred.",
                        "rating_inadequate": "SEM calculated based on Cronbach's alpha or SD from another population. OR (SEM_consistency, SDC_consistency or LoA calculated) WITH evidence provided that systematic change has occurred.",
                        "na_allowed": True,
                        "sort_order": 4,
                    },
                    {
                        "standard_number": 5,
                        "question_text": "For dichotomous/nominal/ordinal scores: was the percentage (positive and negative) agreement calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "% positive and negative agreement calculated.",
                        "rating_adequate": "% agreement calculated.",
                        "rating_doubtful": "",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 5,
                    },
                    {
                        "standard_number": 6,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 6,
                    },
                ],
            },
        ],
    },
    # ========================================================================
    # BOX 8: CRITERION VALIDITY
    # ========================================================================
    {
        "box_number": 8,
        "name": "Criterion validity",
        "description": "Evaluates the degree to which the scores of a PROM are an adequate reflection of a gold standard.",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "8",
                "name": "Criterion validity",
                "section_group": "Criterion validity",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "For continuous scores: were correlations, or the AUC calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Correlations or AUC calculated.",
                        "rating_adequate": "",
                        "rating_doubtful": "",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "For dichotomous scores: were sensitivity and specificity determined?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Sensitivity and specificity calculated.",
                        "rating_adequate": "",
                        "rating_doubtful": "",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                ],
            },
        ],
    },
    # ========================================================================
    # BOX 9: HYPOTHESES TESTING FOR CONSTRUCT VALIDITY
    # ========================================================================
    {
        "box_number": 9,
        "name": "Hypotheses testing for construct validity",
        "description": "Evaluates construct validity through hypotheses testing (convergent, discriminant, known-groups).",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "9a",
                "name": "Comparison with other outcome measurement instruments (convergent validity)",
                "section_group": "Convergent validity",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "Is it clear what the comparator instrument(s) measure(s)?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Constructs measured by the comparator instrument(s) is clear.",
                        "rating_adequate": "",
                        "rating_doubtful": "",
                        "rating_inadequate": "Constructs measured by the comparator instrument(s) is not clear.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "Were the measurement properties of the comparator instrument(s) sufficient?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Sufficient measurement properties of the comparator instrument(s) in a population similar to the study population.",
                        "rating_adequate": "Sufficient measurement properties of the comparator instrument(s) but not sure if these apply to the study population.",
                        "rating_doubtful": "Some information on measurement properties of the comparator instrument(s) in any study population.",
                        "rating_inadequate": "No information on the measurement properties of the comparator instrument(s), OR evidence for insufficient measurement properties of the comparator instrument(s).",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "Were statistical methods adequate for the comparisons made?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Statistical methods applied were appropriate.",
                        "rating_adequate": "Assumable that statistical methods were appropriate.",
                        "rating_doubtful": "Statistical methods applied NOT optimal.",
                        "rating_inadequate": "Statistical methods applied NOT appropriate.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 4,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 4,
                    },
                ],
            },
            {
                "sub_box_code": "9b",
                "name": "Comparison between subgroups (discriminative or known-groups validity)",
                "section_group": "Discriminant/Known-groups",
                "sort_order": 2,
                "standards": [
                    {
                        "standard_number": 5,
                        "question_text": "Was an adequate description provided of important characteristics of the subgroups?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Adequate description of the important characteristics of the subgroups.",
                        "rating_adequate": "Adequate description of most of the important characteristics of the subgroups.",
                        "rating_doubtful": "Poor or no description of the important characteristics of the subgroups.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 6,
                        "question_text": "Were statistical methods appropriate for the subgroups being compared?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Statistical methods applied were appropriate.",
                        "rating_adequate": "Assumable that statistical methods were appropriate.",
                        "rating_doubtful": "Statistical methods applied NOT optimal.",
                        "rating_inadequate": "Statistical methods applied NOT appropriate.",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 7,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                ],
            },
        ],
    },
    # ========================================================================
    # BOX 10: RESPONSIVENESS
    # ========================================================================
    {
        "box_number": 10,
        "name": "Responsiveness",
        "description": "Evaluates the ability of a PROM to detect change over time in the construct to be measured.",
        "prerequisite": None,
        "sub_boxes": [
            {
                "sub_box_code": "10a",
                "name": "Criterion approach (i.e. comparison to a gold standard)",
                "section_group": "Criterion approach",
                "sort_order": 1,
                "standards": [
                    {
                        "standard_number": 1,
                        "question_text": "For continuous scores: were correlations between change scores, or the AUC calculated?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Correlations or AUC calculated.",
                        "rating_adequate": "",
                        "rating_doubtful": "",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 2,
                        "question_text": "For dichotomous scales: were sensitivity and specificity (changed versus not changed) determined?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Sensitivity and specificity calculated.",
                        "rating_adequate": "",
                        "rating_doubtful": "",
                        "rating_inadequate": "",
                        "na_allowed": True,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 3,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                ],
            },
            {
                "sub_box_code": "10b",
                "name": "Construct approach (i.e. hypotheses testing; comparison with other outcome measurement instruments)",
                "section_group": "Construct - instruments",
                "sort_order": 2,
                "standards": [
                    {
                        "standard_number": 4,
                        "question_text": "Is it clear what the comparator instrument(s) measure(s)?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Constructs measured by the comparator instrument(s) is clear.",
                        "rating_adequate": "",
                        "rating_doubtful": "",
                        "rating_inadequate": "Constructs measured by the comparator instrument(s) is not clear.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 5,
                        "question_text": "Were the measurement properties of the comparator instrument(s) sufficient?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Sufficient measurement properties of the comparator instrument(s) in a population similar to the study population.",
                        "rating_adequate": "Sufficient measurement properties of the comparator instrument(s) but not sure if these apply to the study population.",
                        "rating_doubtful": "Some information on measurement properties of the comparator instrument(s) in any study population.",
                        "rating_inadequate": "NO information on the measurement properties of the comparator instrument(s) OR evidence of poor quality of comparator instrument(s).",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 6,
                        "question_text": "Were statistical methods appropriate for the comparisons being made?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Statistical methods applied appropriate.",
                        "rating_adequate": "Assumable that statistical methods were appropriate.",
                        "rating_doubtful": "Statistical methods applied NOT optimal.",
                        "rating_inadequate": "Statistical methods applied NOT appropriate.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                    {
                        "standard_number": 7,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 4,
                    },
                ],
            },
            {
                "sub_box_code": "10c",
                "name": "Construct approach (i.e. hypotheses testing; comparison between subgroups)",
                "section_group": "Construct - subgroups",
                "sort_order": 3,
                "standards": [
                    {
                        "standard_number": 8,
                        "question_text": "Was an adequate description provided of important characteristics of the subgroups?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Adequate description of the important characteristics of the subgroups.",
                        "rating_adequate": "Adequate description of most of the important characteristics of the subgroups.",
                        "rating_doubtful": "Poor or no description of the important characteristics of the subgroups.",
                        "rating_inadequate": "",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 9,
                        "question_text": "Were statistical methods appropriate for the subgroups being compared?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Statistical methods applied appropriate.",
                        "rating_adequate": "Assumable that statistical methods were appropriate.",
                        "rating_doubtful": "Statistical method applied NOT optimal.",
                        "rating_inadequate": "Statistical method applied NOT appropriate.",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 10,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                ],
            },
            {
                "sub_box_code": "10d",
                "name": "Construct approach (i.e. hypotheses testing; before and after intervention)",
                "section_group": "Construct - intervention",
                "sort_order": 4,
                "standards": [
                    {
                        "standard_number": 11,
                        "question_text": "Was an adequate description provided of the intervention given?",
                        "section_group": "Design requirements",
                        "rating_very_good": "Adequate description of the intervention.",
                        "rating_adequate": "",
                        "rating_doubtful": "Poor description of the intervention.",
                        "rating_inadequate": "NO description of the intervention.",
                        "na_allowed": False,
                        "sort_order": 1,
                    },
                    {
                        "standard_number": 12,
                        "question_text": "Were statistical methods appropriate for the before-after comparison being made?",
                        "section_group": "Statistical methods",
                        "rating_very_good": "Statistical methods applied appropriate.",
                        "rating_adequate": "Assumable that statistical methods were appropriate.",
                        "rating_doubtful": "Statistical methods applied NOT optimal.",
                        "rating_inadequate": "Statistical methods applied NOT appropriate.",
                        "na_allowed": False,
                        "sort_order": 2,
                    },
                    {
                        "standard_number": 13,
                        "question_text": "Were there any other important flaws in the design or statistical methods of the study?",
                        "section_group": "Other",
                        "rating_very_good": "No other important methodological flaws.",
                        "rating_adequate": "",
                        "rating_doubtful": "Other minor methodological flaws.",
                        "rating_inadequate": "Other important methodological flaws.",
                        "na_allowed": False,
                        "sort_order": 3,
                    },
                ],
            },
        ],
    },
]
